# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87fbffd82a657528015ef8de8b2c2550de7aa6301d4f1c7927322d0e11800c99834e552ad4f1a32f634117ff6ca2af52e9b45d76b96d0a56c6ef50f4e764ef95

test:
  secret_key_base: e10a9f914e3bf8bbb2c2fbb86a5916112af0ae971593603e311219146d264faf037fa888ed041cbdec01ae411afba5d005b5bccf27f826f6ee62176f4f059f5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
